Cep\Entity\SchoolRequest:
  type: entity
  table: schoolreq
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    created_time:
      type: datetime
      notnull: true
    requester_name:
      type: string(50)
      notnull: true
    requester_type:
      type: boolean
      notnull: true
    school_name:
      type: string(50)
      notnull: true
    school_city:
      type: string(20)
      notnull: true
    contact_name:
      type: string(50)
      notnull: true
    contact_info:
      type: string(300)
      notnull: true
  lifecycleCallbacks: {  }
